export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    CHECK_USER: "user/CHECK_USER",
    GOOGLE_SIGN_IN_START: "user/GOOGLE_SIGN_IN_START",
    EMAIL_SIGN_IN_START: "user/USER_SIGN_IN_START",
    SIGN_UP_START: "user/SIGN_UP_START",
    SIGN_UP_SUCCESS: "user/SIGN_UP_SUCCESS",
    SIGN_UP_FAILED: "user/SIGN_UP_FAILED",
    SIGN_IN_SUCCESS: "user/SIGN_IN_SUCCESS",
    SIGN_IN_FAILED: "user/SIGN_IN_FAILED"
};